name: adsdhotel

services:
- name: rabbit
  image: rabbitmq:management-alpine
  tags:
    - inf
  bindings:
    - name: rabbit
      port: 5672
      protocol: amqp
    - name: ui
      port: 15672
      containerPort: 15672
      protocol: http

- name: mongodb
  image: mongo
  tags:
    - inf
    - db
  bindings:
    - name: mongodb
      port: 27017
      protocol: mongodb
      containerPort: 27017

- name: mysql
  image: mysql
  tags:
    - inf
    - db
  bindings:
    - name: mysql
      port: 3306
      containerPort: 3306
  env:
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: true

- name: blackservice
  project: black\src\api\artiso.AdsdHotel.Black.Api.csproj
  tags:
    - black
    - api

- name: blueservice
  project: blue\src\api\artiso.AdsdHotel.Blue.Api.csproj
  tags:
    - blue
    - api
    - app

- name: yellowservice
  project: yellow\src\api\artiso.AdsdHotel.Yellow.Api.csproj
  tags:
    - yellow
    - api

- name: redservice
  project: red\src\api\artiso.AdsdHotel.Red.Api.csproj
  tags:
    - red
    - api
  bindings:
    - name: grpc
      port: 5001
      containerPort: 5001

- name: purpleservice
  project: purple\src\api\artiso.AdsdHotel.Purple.Api.csproj
  tags:
    - purple
    - api
