# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
# define global settings here
name: adsd-black # application name
# registry: exampleuser # dockerhub username or container registry hostname

# define multiple services here
services:
- name: blackservice
  project: src\api\artiso.AdsdHotel.Black.Api.csproj # msbuild project path (relative to this file)
- name: rabbit
  image: rabbitmq:management-alpine
  bindings:
    - name: rabbit
      port: 5672
      protocol: amqp
      #connectionString: host=${host}
    - name: ui
      port: 15672  
      containerPort: 15672
      protocol: http

  # executable: app.exe # path to an executable (relative to this file)
  # args: --arg1=3 # arguments to pass to the process
  # replicas: 5 # number of times to launch the application
  # env: # array of environment variables
  #  - name: key
  #    value: value
  # bindings: # optional array of bindings (ports, connection strings)
    # - port: 8080 # number port of the binding
